language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - "node_modules"
script:
  - "npm run build"
  - "npm test"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"